#!/bin/sh
export {{ cookiecutter.name | upper }}_ADMIN="./etc/config/base.py|./etc/config/admin.py"
{%- if cookiecutter.has_api %}
export {{ cookiecutter.name | upper }}_API="./etc/config/base.py|./etc/config/api.py"
{%- endif %}
{%- if cookiecutter.has_web %}
export {{ cookiecutter.name | upper }}_WEB="./etc/config/base.py|./etc/config/web.py"
{%- endif %}
