#!/bin/sh
export {{ cookiecutter.name | upper }}_ADMIN="/home/{{ cookiecutter.name }}/{{ cookiecutter.name }}/etc/admin.cfg"
{%- if cookiecutter.has_api %}
export {{ cookiecutter.name | upper }}_API="/home/{{ cookiecutter.name }}/{{ cookiecutter.name }}/etc/api.cfg"
{%- endif %}
{%- if cookiecutter.has_web %}
export {{ cookiecutter.name | upper }}_WEB="/home/{{ cookiecutter.name }}/{{ cookiecutter.name }}/etc/web.cfg"
{%- endif %}

alias chk="cd ~/{{ cookiecutter.name }}"
alias admin-start="uwsgi --ini ~/{{ cookiecutter.name }}/etc/uwsgi-admin.ini"
alias admin-stop="uwsgi --stop ~/{{ cookiecutter.name }}/run/admin.pid"
alias admin-reload="uwsgi --reload ~/{{ cookiecutter.name }}/run/admin.pid"
{%- if cookiecutter.has_api %}

alias api-start="uwsgi --ini ~/{{ cookiecutter.name }}/etc/uwsgi-api.ini"
alias api-stop="uwsgi --stop ~/{{ cookiecutter.name }}/run/api.pid"
alias api-reload="uwsgi --reload ~/{{ cookiecutter.name }}/run/api.pid"
{%- endif %}
{%- if cookiecutter.has_web %}

alias web-start="uwsgi --ini ~/{{ cookiecutter.name }}/etc/uwsgi-web.ini"
alias web-stop="uwsgi --stop ~/{{ cookiecutter.name }}/run/web.pid"
alias web-reload="uwsgi --reload ~/{{ cookiecutter.name }}/run/web.pid"
{%- endif %}

{% if cookiecutter.has_api and cookiecutter.has_web %}
alias uwsgi-start="admin-start && api-start && web-start"
alias uwsgi-stop="admin-stop && api-stop && web-stop"
alias uwsgi-reload="admin-reload && api-reload && web-reload"
{% elif cookiecutter.has_api %}
alias uwsgi-start="admin-start && api-start"
alias uwsgi-stop="admin-stop && api-stop"
alias uwsgi-reload="admin-reload && api-reload"
{% elif cookiecutter.has_web %}
alias uwsgi-start="admin-start && web-start"
alias uwsgi-stop="admin-stop && web-stop"
alias uwsgi-reload="admin-reload && web-reload"
{% else %}
alias uwsgi-start="admin-start"
alias uwsgi-stop="admin-stop"
alias uwsgi-reload="admin-reload"
{% endif %}

source /usr/local/bin/virtualenvwrapper.sh
workon {{ cookiecutter.name }}
cd ~/{{ cookiecutter.name }}